# DWDDRandomizer Settings Export
# Generated: 2026-02-06 22:32:54

[app_data]
APP_VERSION = "0.1.1"
ROM_VERSION = "DUSK_US"
SEED = -1

[randomizer_options]
INCREASE_TEXT_SPEED = true
INCREASE_MOVEMENT_SPEED = true
EXPAND_PLAYER_NAME_LENGTH = true
IMPROVE_BATTLE_PERFORMANCE = true
REDUCE_WILD_ENCOUNTER_RATE = true
INCREASE_SCAN_RATE = true
INCREASE_DIGIMON_EXP = 1
INCREASE_WILD_ENCOUNTER_MONEY = true
INCREASE_FARM_EXP = true
BALANCE_CALUMON_STATS = true
ENABLE_LEGENDARY_TAMER_QUEST = true
UNLOCK_MAIN_QUESTS_IN_SEQUENCE = true
UNLOCK_VERSION_EXCLUSIVE_AREAS = true
RANDOMIZE_STARTERS = 2
CUSTOM_STARTER_PACKS = [ [ "MachGaogamon", "Lunamon", "Clockmon",], [ "SkullGreymon", "Lunamon", "WarGarurumon(Black)",], [ "Megakabuterimon(Blue)", "Lunamon", "Kurisarimon",], [ "Pandamon", "Lunamon", "Lillymon",],]
NERF_FIRST_BOSS = false
FORCE_STARTER_W_ROOKIE_STAGE = false
ROOKIE_RESET_EVENT = 2
RANDOMIZE_OVERWORLD_ITEMS = 2
RANDOMIZE_QUEST_ITEM_REWARDS = 2
RANDOMIZE_WILD_DIGIMON_ENCOUNTERS = 2
RANDOMIZE_WILD_ENCOUNTER_ITEMS = 2
WILD_ENCOUNTERS_STATS = 3
RANDOMIZE_FIXED_BATTLES = 2
RANDOMIZE_DIGIMON_SPECIES = 1
SPECIES_ALLOW_UNKNOWN = true
RANDOMIZE_ELEMENTAL_RESISTANCES = 2
KEEP_SPECIES_RESISTANCE_COHERENCE = false
RANDOMIZE_BASE_STATS = 3
BASESTATS_STATTYPE_BIAS = false
RANDOMIZE_DIGIMON_STATTYPE = 1
RANDOMIZE_MOVESETS = 2
MOVESETS_LEVEL_BIAS = false
REGULAR_MOVE_POWER_BIAS = false
SIGNATURE_MOVE_POWER_BIAS = false
MOVESETS_SIGNATURE_MOVES_POOL = true
MOVESETS_GUARANTEE_BASIC_MOVE = false
RANDOMIZE_TRAITS = 2
TRAITS_FORCE_FOUR = true
TRAITS_ENABLE_UNUSED = true
RANDOMIZE_DIGIVOLUTIONS = 1
DIGIVOLUTIONS_SIMILAR_SPECIES = false
RANDOMIZE_DIGIVOLUTION_CONDITIONS = 1
DIGIVOLUTION_CONDITIONS_FOLLOW_SPECIES_EXP = false
RANDOMIZE_DNADIGIVOLUTIONS = 2
RANDOMIZE_DNADIGIVOLUTION_CONDITIONS = 1
DNADIGIVOLUTION_CONDITIONS_FOLLOW_SPECIES_EXP = false
