# DWDDRandomizer Settings Export
# Generated: 2026-02-06 22:33:35

[app_data]
APP_VERSION = "0.1.1"
ROM_VERSION = "DUSK_US"
SEED = -1

[randomizer_options]
INCREASE_TEXT_SPEED = true
INCREASE_MOVEMENT_SPEED = true
EXPAND_PLAYER_NAME_LENGTH = true
IMPROVE_BATTLE_PERFORMANCE = true
REDUCE_WILD_ENCOUNTER_RATE = false
INCREASE_SCAN_RATE = false
INCREASE_DIGIMON_EXP = 0
INCREASE_WILD_ENCOUNTER_MONEY = false
INCREASE_FARM_EXP = false
BALANCE_CALUMON_STATS = true
ENABLE_LEGENDARY_TAMER_QUEST = true
UNLOCK_MAIN_QUESTS_IN_SEQUENCE = false
UNLOCK_VERSION_EXCLUSIVE_AREAS = false
RANDOMIZE_STARTERS = 0
CUSTOM_STARTER_PACKS = [ [ "MachGaogamon", "Lunamon", "Clockmon",], [ "SkullGreymon", "Lunamon", "WarGarurumon(Black)",], [ "Megakabuterimon(Blue)", "Lunamon", "Kurisarimon",], [ "Pandamon", "Lunamon", "Lillymon",],]
NERF_FIRST_BOSS = false
FORCE_STARTER_W_ROOKIE_STAGE = false
ROOKIE_RESET_EVENT = 0
RANDOMIZE_OVERWORLD_ITEMS = 0
RANDOMIZE_QUEST_ITEM_REWARDS = 0
RANDOMIZE_WILD_DIGIMON_ENCOUNTERS = 0
RANDOMIZE_WILD_ENCOUNTER_ITEMS = 0
WILD_ENCOUNTERS_STATS = 0
RANDOMIZE_FIXED_BATTLES = 0
RANDOMIZE_DIGIMON_SPECIES = 0
SPECIES_ALLOW_UNKNOWN = false
RANDOMIZE_ELEMENTAL_RESISTANCES = 0
KEEP_SPECIES_RESISTANCE_COHERENCE = false
RANDOMIZE_BASE_STATS = 0
BASESTATS_STATTYPE_BIAS = false
RANDOMIZE_DIGIMON_STATTYPE = 0
RANDOMIZE_MOVESETS = 0
MOVESETS_LEVEL_BIAS = false
REGULAR_MOVE_POWER_BIAS = false
SIGNATURE_MOVE_POWER_BIAS = false
MOVESETS_SIGNATURE_MOVES_POOL = false
MOVESETS_GUARANTEE_BASIC_MOVE = false
RANDOMIZE_TRAITS = 0
TRAITS_FORCE_FOUR = false
TRAITS_ENABLE_UNUSED = false
RANDOMIZE_DIGIVOLUTIONS = 0
DIGIVOLUTIONS_SIMILAR_SPECIES = false
RANDOMIZE_DIGIVOLUTION_CONDITIONS = 0
DIGIVOLUTION_CONDITIONS_FOLLOW_SPECIES_EXP = false
RANDOMIZE_DNADIGIVOLUTIONS = 0
RANDOMIZE_DNADIGIVOLUTION_CONDITIONS = 0
DNADIGIVOLUTION_CONDITIONS_FOLLOW_SPECIES_EXP = false
